<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ctu</string>
	</array>
	<key>name</key>
	<string>Continue</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block definition with bound name and argument</string>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9_]*)[ 	]*(=)[ 	]*{[ 	]*('[a-zA-Z][a-zA-Z0-9_]*)?[ 	]*([^-&gt;]*)(-&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block definition with bound name</string>
			<key>match</key>
			<string>([a-zA-Z][a-zA-Z0-9_]*)[ 	]*(=)[ 	]*{[ 	]*('[a-zA-Z][a-zA-Z0-9_]*)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block definition with argument</string>
			<key>match</key>
			<string>{[ 
	]*('[a-zA-Z][a-zA-Z0-9_]*)?[ 	]*([^-&gt;]*)(-&gt;)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block definition</string>
			<key>match</key>
			<string>{[ 
	]*('[a-zA-Z][a-zA-Z0-9_]*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>as</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true|false)</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9_]*'[a-zA-Z][a-zA-Z0-9_]*(!)?</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9_]*!</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-+*/&lt;&gt;=&amp;|!?:_%]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ctu</string>
	<key>uuid</key>
	<string>2953674d-ce89-4913-9be2-dbff2a143d49</string>
</dict>
</plist>
